[build-system]
requires = [
    #"setuptools>=42",
    #"scikit-build>=0.3.3",
    "scikit-build-core",
    "cmake>=3.18",
    "ninja",
    "pybind11"
]
#build-backend = "setuptools.build_meta"
build-backend = "scikit_build_core.build"

[project]
name = "ugpip_build_simplest"
version = "0.0.1"
