[build-system]
requires = [
    #"setuptools>=42",
    #"scikit-build>=0.3.3",
    "scikit-build-core",
    "cmake>=3.18",
    "ninja",
    "pybind11"
]
#build-backend = "setuptools.build_meta"
build-backend = "scikit_build_core.build"

[project]
name = "ugpip_build_simplest"
version = "0.0.1"

[tool.scikit-build]
#  cf. https://github.com/scikit-build/scikit-build-core

# DEPRECATED in 0.8; use version instead.
cmake.minimum-version = ""

# The versions of CMake to allow. If CMake is not present on the system or does
# not pass this specifier, it will be downloaded via PyPI if possible. An empty
# string will disable this check.
cmake.version = ">=3.15"

#
logging.level = "DEBUG"
