name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
      #  os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [ubuntu-latest]

    steps:
      # - uses: actions/checkout@v4

      ## Used to host cibuildwheel
      #- uses: actions/setup-python@v3

      - name: Checkout ughub
        uses: actions/checkout@v4
        with:
          repository: UG4/ughub
          path: ughub

      - name: Checkout ugcore
        uses: actions/checkout@v4
        with:
          repository: UG4/ugcore
          path: ugcore



      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "pyproject.toml"
          # config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
        
