name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest]
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:

      ## Used to host cibuildwheel
      #- uses: actions/setup-python@v3
      - name: Checkout self
        uses: actions/checkout@v4
      
      - name: Checkout ughub
        uses: actions/checkout@v4
        with:
          repository: UG4/ughub
          path: ughub
        
      - name: Install UG4 packages
        run: |
          python ughub/ughub.py init
          python ughub/ughub.py install Limex

      #- name: Checkout ugcore
      #  uses: actions/checkout@v4
      #  with:
      #    repository: UG4/ugcore
      #    path: ugcore

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_BUILD_VERBOSITY:  1
          CIBW_REPAIR_WHEEL_COMMAND: ''
          CIBW_BUILD: cp310-*
          # Skip builds for 32-bit builds and some others...
          CIBW_SKIP: "*-win32 *musllinux* *linux_i686 *linux_s390x *linux_aarch64 *linux_s390x" 
          
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        with:
          package-dir: .
          output-dir: wheelhouse
          # config-file: "pyproject.toml"
          config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
        
